### ISSUE TITLE
Porting: add monitoring-models-with-openscale-gui

### ISSUE THREAD

**Issue by scottdangelo** [IBM/credit-risk-workshop-cpd#21]
port from `https://github.com/IBM/cloudpakfordata-telco-churn-workshop`                                        
  
* Add and modify monitoring-models-with-openscale-gui.
* update images

**Comment by scottdangelo** [comment]
Code is in, images need updating.

**Comment by jrtorres** [comment]
@scottdangelo , i think we should close here and keep tracking in upstream

**Comment by jrtorres** [comment]
tracking in upstream
