### ISSUE TITLE
Update: WKC for multiple roles, including pre-populated catalog(s)

### ISSUE THREAD

**Issue by scottdangelo** [IBM/credit-risk-workshop-cpd#36]
Update for 3 roles: Admin, Editor (Data Steward), and Viewer (Data Scientist).
Utilize any existing WKC tools to import pre-built catalogs, -or-
Use the API to create Catalog(s), Business Terms, Policies, etc.

**Comment by jrtorres** [comment]
two paths delivered for WKC module as Admin and viewer.
