### ISSUE TITLE
Broken Link in ML with Jupyter module

### ISSUE THREAD

**Issue by jrtorres** [IBM/credit-risk-workshop-cpd#46]
This link "Notebook with output: with-output/credit-risk-notebook-with-output.ipynb" is broken

**Comment by scottdangelo** [comment]
FYI, this is due to git not being able to differentiate between `Jupyter` and `jupyter`. I'll get a workaround in the repo.

**Comment by jrtorres** [comment]
fixed by pr #51 and #52
